[2025-06-29T04:57:20.141+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: films_dag_orchestaror.run_etl_script scheduled__2025-06-29T02:10:00+00:00 [queued]>
[2025-06-29T04:57:20.154+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: films_dag_orchestaror.run_etl_script scheduled__2025-06-29T02:10:00+00:00 [queued]>
[2025-06-29T04:57:20.155+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-29T04:57:20.189+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_etl_script> on 2025-06-29 02:10:00+00:00
[2025-06-29T04:57:20.196+0000] {standard_task_runner.py:60} INFO - Started process 6972 to run task
[2025-06-29T04:57:20.201+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'films_dag_orchestaror', 'run_etl_script', 'scheduled__2025-06-29T02:10:00+00:00', '--job-id', '1733', '--raw', '--subdir', 'DAGS_FOLDER/orchestrator.py', '--cfg-path', '/tmp/tmpgh9qco4h']
[2025-06-29T04:57:20.204+0000] {standard_task_runner.py:88} INFO - Job 1733: Subtask run_etl_script
[2025-06-29T04:57:20.295+0000] {task_command.py:423} INFO - Running <TaskInstance: films_dag_orchestaror.run_etl_script scheduled__2025-06-29T02:10:00+00:00 [running]> on host 1b1e07855000
[2025-06-29T04:57:20.428+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='films_dag_orchestaror' AIRFLOW_CTX_TASK_ID='run_etl_script' AIRFLOW_CTX_EXECUTION_DATE='2025-06-29T02:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-29T02:10:00+00:00'
[2025-06-29T04:57:20.583+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/orchestrator.py", line 18, in run_etl_script
    raise Exception(result.stderr)
Exception: pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 17.5 (Debian 17.5-1.pgdg120+1); pg_dump version: 16.2 (Debian 16.2-1.pgdg120+2)
Traceback (most recent call last):
  File "/opt/airflow/etl/etl.py", line 61, in <module>
    subprocess.run(dump_comand,env=subprocess_env,check=True)
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pg_dump', '-h', 'source_postgres', '-U', 'postgres', '-d', 'source_db', '-f', 'data_dump.sql', '-w']' returned non-zero exit status 1.

[2025-06-29T04:57:20.601+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=films_dag_orchestaror, task_id=run_etl_script, execution_date=20250629T021000, start_date=20250629T045720, end_date=20250629T045720
[2025-06-29T04:57:20.619+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1733 for task run_etl_script (pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 17.5 (Debian 17.5-1.pgdg120+1); pg_dump version: 16.2 (Debian 16.2-1.pgdg120+2)
Traceback (most recent call last):
  File "/opt/airflow/etl/etl.py", line 61, in <module>
    subprocess.run(dump_comand,env=subprocess_env,check=True)
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pg_dump', '-h', 'source_postgres', '-U', 'postgres', '-d', 'source_db', '-f', 'data_dump.sql', '-w']' returned non-zero exit status 1.
; 6972)
[2025-06-29T04:57:20.627+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-29T04:57:20.654+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-29T05:40:06.490+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: films_dag_orchestaror.run_etl_script scheduled__2025-06-29T02:10:00+00:00 [queued]>
[2025-06-29T05:40:06.501+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: films_dag_orchestaror.run_etl_script scheduled__2025-06-29T02:10:00+00:00 [queued]>
[2025-06-29T05:40:06.502+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-29T05:40:06.525+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_etl_script> on 2025-06-29 02:10:00+00:00
[2025-06-29T05:40:06.530+0000] {standard_task_runner.py:60} INFO - Started process 9698 to run task
[2025-06-29T05:40:06.533+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'films_dag_orchestaror', 'run_etl_script', 'scheduled__2025-06-29T02:10:00+00:00', '--job-id', '1574', '--raw', '--subdir', 'DAGS_FOLDER/orchestrator.py', '--cfg-path', '/tmp/tmphikaawi8']
[2025-06-29T05:40:06.536+0000] {standard_task_runner.py:88} INFO - Job 1574: Subtask run_etl_script
[2025-06-29T05:40:06.602+0000] {task_command.py:423} INFO - Running <TaskInstance: films_dag_orchestaror.run_etl_script scheduled__2025-06-29T02:10:00+00:00 [running]> on host b83c7b21874f
[2025-06-29T05:40:06.721+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='films_dag_orchestaror' AIRFLOW_CTX_TASK_ID='run_etl_script' AIRFLOW_CTX_EXECUTION_DATE='2025-06-29T02:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-29T02:10:00+00:00'
